# Halloy config.
#
# For a complete list of available options,
# please visit https://halloy.chat/configuration.html

[servers.liberachat]
nickname = "__NICKNAME__"
server = "irc.libera.chat"
channels = ["#halloy"]
