# Configuration sample file for Halloy.
# Place this in your user's config directory:
#
# Linux: `$HOME`/.config/halloy
# macOS: `$HOME`/Library/Application Support/halloy
# Windows: `{FOLDERID_RoamingAppData}`\halloy

palette:
  background: "#2b292d"
  text: "#fecdb2"
  action: "#b1b695"
  accent: "#d1d1e0"
  alert: "#ffa07a"
  error: "#e06b75"
  info: "#f5d76e"
  success: "#b1b695"

# For fields under server, please refer to: https://docs.rs/irc/0.15.0/irc/client/data/config/struct.Config.html#fields

servers:
  - nickname: halloy
    server: irc.libera.chat
    port: 6697
    use_tls: true
    channels:
      - "##rust"