# Configuration sample file for Halloy.
# Place this in your user's config directory:
#
# Linux: `$HOME`/.config/halloy
# macOS: `$HOME`/Library/Application Support/halloy
# Windows: `{FOLDERID_RoamingAppData}`\halloy
palette:
  background: "#2b292d"
  text: "#fecdb2"
  action: "#b1b695"
  accent: "#d1d1e0"
  alert: "#ffa07a"
  error: "#e06b75"
  info: "#f5d76e"
  success: "#b1b695"

# For more fields under server, please refer to:
# https://docs.rs/irc/0.15.0/irc/client/data/config/struct.Config.html#fields
servers:
  # Configuration for Libera server
  liberachat:
    # Nickname to be used on the server
    nickname: halloy
    
    # Server address
    server: irc.libera.chat
    
    # Server port number
    port: 6697
    
    # Whether to use TLS
    use_tls: true
    
    # Channels to join upon connecting to the server
    channels:
      - "#halloy"

# Font settings
font: 
  # Specify the monospaced font family to use
  # - Default is Iosevka Term and provided by this application
  family: Iosevka Term
  # Specify the font size
  # - Default is 13
  size: 13
      
# Settings applied by default to new buffers
new_buffer:
  # Nickname settings
  nickname:
    # User color settings:
    # - Unique: Unique user colors [default]
    # - Solid: Solid user colors
    color: Unique
    
    # Nickname brackets:
    # - Default is empty ""
    brackets:
      left: "<"
      right: ">"
      
  # Timestamp settings
  timestamp: 
    # Timestamp format:
    # - Use `strftime` format (see documentation for details):
    #   https://pubs.opengroup.org/onlinepubs/007908799/xsh/strftime.html
    format: "%T"
    
    # Timestamp brackets:
    # - Default is empty ""
    brackets:
      left: "["
      right: "]"

  # Channel buffer settings
  channel:
    # User list settings
    users:
      # Visible by default
      # - Default is true
      visible: true
      # List position
      # - Left: Left side of pane
      # - Right: Right side of pane [default]
      position: Right  
