# Halloy config.
#
# For a complete list of available options,
# please visit https://halloy.squidowl.org/configuration/index.html

[servers.liberachat]
nickname = "__NICKNAME__"
server = "irc.libera.chat"
channels = ["#halloy"]
