[general]
background = "#452859"
horizontal_rule = "#54326F"
unread_indicator = "#36BF86"
border = "#DBBFEF"

[text]
primary = "#D8C8F3"
secondary = "#ad96be"
tertiary = "#ECCDBA"
success = "#A0F28F"
error = "#F47868"

[buffer]
background = "#3A224C"
background_text_input = "#311D41"
background_title_bar = "#362047"
timestamp = "#806d8d"
action = "#E8DCA0"
topic = "#DBBFEF"
highlight = "#64546f"
code = "#CCCCCC"
nickname = "#A0F28F"
url = "#82CECF"
selection = "#50496d"
border_selected = "#A4A0E8"

[buffer.server_messages]
default = "#FFCD1D"

[buttons.primary]
background_hover = "#4A2B5F"
background_selected = "#54316C"
background_selected_hover = "#56326E"

[buttons.secondary]
background = "#3F2653"
background_hover = "#44295A"
background_selected = "#857293"
background_selected_hover = "#c1a8d3"
