[colors.general]
background = "#161616"
horizontal_rule = "#262626"
unread_indicator = "#be95ff"
border = "#262626"

[colors.text]
primary = "#f2f4f8"
secondary = "#525252"
tertiary = "#be95ff"
success = "#42be65"
error = "#ee5396"

[colors.buffer]
background = "#161616"
background_text_input = "#1f1e1e"
background_title_bar = "#1c1c1c"
timestamp = "#393939"
action = "#3ddbd9"
topic = "#525252"
highlight = "#40364f"
code = "#be95ff"
nickname = "#42be65"
url = "#78a9ff"
selection = "#30293A"
border_selected = "#262626"
border = "#262626"

[colors.buffer.server_messages]
default = "#ff7eb6"

[colors.buttons.primary]
background = "#161616"
background_hover = "#262626"
background_selected = "#262626"
background_selected_hover = "#161616"

[colors.buttons.secondary]
background = "#242424"
background_hover = "#282828"
background_selected = "#40364f"
background_selected_hover = "#514367"
