verbose = "info"
no_progress = true

include_fragments = true
root_dir = "book/src"

# Reduce rate of checks to respect limits
max_retries = 1 # default: 3
retry_wait_time = 5 # seconds, default: 1
max_concurrency = 32 # default: 128

exclude_all_private = true
exclude = [ '.*' ]
include = [ '^http://.*', '^https://.*' ]
