[package]
name = "irc"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.4.0"
futures = "0.3.28"
thiserror = "1.0.30"
tokio = { version = "1.29", features = ["net", "full"] }
tokio-native-tls = "0.3.1"
tokio-util = { version = "0.7", features = ["codec"] }

[dependencies.proto]
path = "proto"
package = "irc_proto"
