name: Book

on:
  pull_request:
    paths:
      - 'book/**.md'
      - 'book/book.toml'
  push:
    branches:
      - main
    paths:
      - 'book/**.md'
      - 'book/book.toml'
  merge_group:
    paths:
      - 'book/**.md'
      - 'book/book.toml'

jobs:
  build-linkcheck:
    name: Build & Link Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Check internal links
        id: lychee-interal
        uses: lycheeverse/lychee-action@v2
        with:
          args: --config ./.config/lychee-internal.toml './book/**/*.md'
          fail: true

      - name: Check external links
        id: lychee-external
        uses: lycheeverse/lychee-action@v2
        with:
          args: --config ./.config/lychee-external.toml './book/**/*.md'
          fail: true
        continue-on-error: true

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Build book
        run: mdbook build book
